### ISSUE TITLE
Vercel setup of Dub Error

### ISSUE THREAD

**Issue by love2wind** [steven-tey/dub#140]
[01:01:05.952] Cloning github.com/love2wind/dub (Branch: main, Commit: a40b188)
[01:01:05.960] Skipping build cache since Vercel CLI used --force option
[01:01:06.430] Cloning completed: 477.253ms
[01:01:06.909] Running "vercel build"
[01:01:07.636] Vercel CLI 28.9.0
[01:01:08.147] Installing dependencies...
[01:01:08.637] yarn install v1.22.17
[01:01:08.739] [1/4] Resolving packages...
[01:01:09.206] [2/4] Fetching packages...
[01:01:44.192] [3/4] Linking dependencies...
[01:01:44.206] warning " > focus-trap-react@10.0.1" has unmet peer dependency "prop-types@^15.8.1".
[01:01:44.207] warning "mailing-core > mjml-react > react-reconciler@0.26.2" has incorrect peer dependency "react@^17.0.2".
[01:01:44.208] warning "react-hot-toast > goober@2.1.11" has unmet peer dependency "csstype@^3.0.10".
[01:01:44.209] warning "react-spring > @react-spring/konva@9.5.5" has unmet peer dependency "konva@>=2.6".
[01:01:44.210] warning "react-spring > @react-spring/konva@9.5.5" has unmet peer dependency "react-konva@^16.8.0 || ^17.0.0".
[01:01:44.210] warning "react-spring > @react-spring/native@9.5.5" has unmet peer dependency "react-native@>=0.58".
[01:01:44.210] warning "react-spring > @react-spring/three@9.5.5" has unmet peer dependency "@react-three/fiber@>=6.0".
[01:01:44.211] warning "react-spring > @react-spring/three@9.5.5" has unmet peer dependency "three@>=0.126".
[01:01:44.213] warning "react-spring > @react-spring/zdog@9.5.5" has unmet peer dependency "react-zdog@>=1.0".
[01:01:44.213] warning "react-spring > @react-spring/zdog@9.5.5" has unmet peer dependency "zdog@>=1.0".
[01:01:44.213] warning " > @trivago/prettier-plugin-sort-imports@4.0.0" has unmet peer dependency "@vue/compiler-sfc@3.x".
[01:01:44.247] warning Workspaces can only be enabled in private projects.
[01:02:00.608] [4/4] Building fresh packages...
[01:02:08.443] $ prisma generate || true
[01:02:09.959] Prisma schema loaded from prisma/schema.prisma
[01:02:11.488] 
[01:02:11.489] ✔ Generated Prisma Client (4.6.1 | library) to ./node_modules/@prisma/client in 264ms
[01:02:11.489] You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
[01:02:11.489] ```
[01:02:11.489] import { PrismaClient } from '@prisma/client'
[01:02:11.490] const prisma = new PrismaClient()
[01:02:11.490] ```
[01:02:11.535] Done in 62.91s.
[01:02:11.584] Detected Next.js version: 13.0.5
[01:02:11.587] Running "yarn run build"
[01:02:11.974] yarn run v1.22.17
[01:02:12.019] $ prisma generate
[01:02:13.558] Prisma schema loaded from prisma/schema.prisma
[01:02:15.164] 
[01:02:15.164] ✔ Generated Prisma Client (4.6.1 | library) to ./node_modules/@prisma/client in 317ms
[01:02:15.164] You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
[01:02:15.164] ```
[01:02:15.165] import { PrismaClient } from '@prisma/client'
[01:02:15.165] const prisma = new PrismaClient()
[01:02:15.165] ```
[01:02:16.227] ┌─────────────────────────────────────────────────────────┐
[01:02:16.227] │  Update available 4.6.1 -> 4.8.0                        │
[01:02:16.228] │  Run the following to update                            │
[01:02:16.228] │    yarn add --dev prisma@latest                         │
[01:02:16.228] │    yarn add @prisma/client@latest                       │
[01:02:16.228] └─────────────────────────────────────────────────────────┘
[01:02:16.243] $ next build
[01:02:16.802] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[01:02:16.802] This information is used to shape Next.js' roadmap and prioritize features.
[01:02:16.802] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[01:02:16.803] https://nextjs.org/telemetry
[01:02:16.803] 
[01:02:16.972] info  - Linting and checking validity of types...
[01:02:29.444] info  - Creating an optimized production build...
[01:02:29.507] warn  - You are using an experimental edge runtime, the API might change.
[01:03:16.570] warn  - Compiled with warnings
[01:03:16.571] 
[01:03:16.571] ./node_modules/@upstash/redis/esm/platforms/nodejs.js
[01:03:16.571] A Node.js API is used (process.version at line: 26) which is not supported in the Edge Runtime.
[01:03:16.571] Learn more: https://nextjs.org/docs/api-reference/edge-runtime
[01:03:16.571] 
[01:03:16.572] Import trace for requested module:
[01:03:16.572] ./node_modules/@upstash/redis/esm/platforms/nodejs.js
[01:03:16.572] ./lib/upstash.ts
[01:03:16.572] 
[01:03:16.572] info  - Collecting page data...
[01:03:24.471] info  - Generating static pages (0/19)
[01:03:24.631] info  - Generating static pages (4/19)
[01:03:24.671] info  - Generating static pages (9/19)
[01:03:24.725] info  - Generating static pages (14/19)
[01:03:24.765] (node:1358) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
[01:03:24.767] (Use `node --trace-warnings ...` to show where the warning was created)
[01:03:24.843] 
[01:03:24.843] Error occurred prerendering page "/metatags". Read more: https://nextjs.org/docs/messages/prerender-error
[01:03:24.843] TypeError: Cannot read properties of undefined (reading 'entities')
[01:03:24.844]     at getExternalUrls (/vercel/path0/.next/server/chunks/5298.js:491:36)
[01:03:24.844]     at getTweet (/vercel/path0/.next/server/chunks/5298.js:504:23)
[01:03:24.845]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[01:03:24.845]     at async Promise.all (index 0)
[01:03:24.845]     at async getStaticProps (/vercel/path0/.next/server/pages/metatags.js:274:20)
[01:03:24.846]     at async renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:384:20)
[01:03:24.846]     at async /vercel/path0/node_modules/next/dist/export/worker.js:248:32
[01:03:24.847]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[01:03:25.677] 
[01:03:25.677] Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
[01:03:25.677] Error: 
[01:03:25.677] Invalid `prisma.user.count()` invocation:
[01:03:25.677] 
[01:03:25.677] 
[01:03:25.678] The table `(not available)` does not exist in the current database.
[01:03:25.678]     at RequestHandler.handleRequestError (/vercel/path0/node_modules/@prisma/client/runtime/index.js:34310:13)
[01:03:25.678]     at RequestHandler.request (/vercel/path0/node_modules/@prisma/client/runtime/index.js:34293:12)
[01:03:25.678]     at async PrismaClient._request (/vercel/path0/node_modules/@prisma/client/runtime/index.js:35273:16)
[01:03:25.678]     at async getStaticProps (/vercel/path0/.next/server/pages/index.js:1790:23)
[01:03:25.679]     at async renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:384:20)
[01:03:25.679]     at async /vercel/path0/node_modules/next/dist/export/worker.js:248:32
[01:03:25.679]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[01:03:25.679] info  - Generating static pages (19/19)
[01:03:25.683] 
[01:03:25.683] > Build error occurred
[01:03:25.688] Error: Export encountered errors on following paths:
[01:03:25.688] 	/
[01:03:25.688] 	/metatags
[01:03:25.688]     at /vercel/path0/node_modules/next/dist/export/index.js:408:19
[01:03:25.688]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[01:03:25.689]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[01:03:25.690]     at async /vercel/path0/node_modules/next/dist/build/index.js:1334:21
[01:03:25.690]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[01:03:25.690]     at async /vercel/path0/node_modules/next/dist/build/index.js:1194:17
[01:03:25.691]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[01:03:25.691]     at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:65:29)
[01:03:25.755] error Command failed with exit code 1.
[01:03:25.755] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[01:03:25.778] Error: Command "yarn run build" exited with 1

**Comment by TSC-Home** [comment]
i have the same porblem

**Comment by sofiane-soufi** [comment]
Did anyone find a solution for this ?

**Comment by TSC-Home** [comment]
> Did anyone find a solution for this ?

No, unfortunately not, I'll try to solve it and then let you know

**Comment by steven-tey** [comment]
This looks like a duplicate of #135 – if you're self-hosting Dub, feel free to get rid of all instances of the static tweets implementation (on the root page `/` and `/metatags`). Those are not required for the app itself, I'm just using them for the marketing pages 😄

**Comment by steven-tey** [comment]
I just pushed up a [commit](https://github.com/steven-tey/dub/commit/62a9066b8ddeaa880e1ca0a5b49089cd87e6d29e) today that would make the repo work even if you don't have any env vars specified (you just wont see the static tweets). Closing this now, sorry for the trouble before y'all!

**Comment by mrhappyma** [comment]
I'm having something that looks like it's probably the same thing, fresh deploy:

```
TypeError: Cannot read properties of null (reading 'id')
--
14:56:40.126 | at /vercel/path0/.next/server/pages/metatags.js:225:38
14:56:40.126 | at Array.map (<anonymous>)
14:56:40.127 | at Metatags (/vercel/path0/.next/server/pages/metatags.js:223:42)
14:56:40.128 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
14:56:40.128 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
14:56:40.128 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
14:56:40.129 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
14:56:40.129 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
14:56:40.130 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
14:56:40.130 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
14:56:40.130 |  
14:56:40.130 | Error occurred prerendering page "/metatags". Read more: https://nextjs.org/docs/messages/prerender-error
14:56:40.130 | TypeError: Cannot read properties of null (reading 'id')
14:56:40.131 | at /vercel/path0/.next/server/pages/metatags.js:225:38
14:56:40.131 | at Array.map (<anonymous>)
14:56:40.131 | at Metatags (/vercel/path0/.next/server/pages/metatags.js:223:42)
14:56:40.131 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
14:56:40.131 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
14:56:40.131 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
14:56:40.131 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
14:56:40.132 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
14:56:40.132 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
14:56:40.132 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
14:56:40.542 | info  - Generating static pages (16/16)
14:56:40.542 |  
14:56:40.542 | > Build error occurred
14:56:40.546 | Error: Export encountered errors on following paths:
14:56:40.546 | /metatags
14:56:40.546 | at /vercel/path0/node_modules/next/dist/export/index.js:425:19
14:56:40.547 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
14:56:40.547 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
14:56:40.547 | at async /vercel/path0/node_modules/next/dist/build/index.js:1422:21
14:56:40.547 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
14:56:40.547 | at async /vercel/path0/node_modules/next/dist/build/index.js:1280:17
14:56:40.547 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
14:56:40.547 | at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:73:29)
14:56:40.641 | error Command failed with exit code 1.
14:56:40.641 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
14:56:40.663 | Error: Command "yarn run build" exited with 1
14:56:40.946 | BUILD_UTILS_SPAWN_1: Command "yarn run build" exited with 1

```

**Comment by love2wind** [comment]
**It's still wrong**
```
[15:53:55.249] Running build in Washington, D.C., USA (East) – iad1
[15:53:55.302] Cloning github.com/love2wind/dub (Branch: main, Commit: 41e6d65)
[15:53:55.308] Skipping build cache, deployment was triggered without cache.
[15:53:55.651] Cloning completed: 349.227ms
[15:53:55.786] Running "vercel build"
[15:53:56.236] Vercel CLI 28.16.15
[15:53:56.514] Installing dependencies...
[15:53:56.811] yarn install v1.22.17
[15:53:56.887] [1/4] Resolving packages...
[15:53:57.203] [2/4] Fetching packages...
[15:54:28.830] [3/4] Linking dependencies...
[15:54:28.839] warning " > focus-trap-react@10.0.1" has unmet peer dependency "prop-types@^15.8.1".
[15:54:28.839] warning "mailing-core > mjml-react > react-reconciler@0.26.2" has incorrect peer dependency "react@^17.0.2".
[15:54:28.840] warning "react-hot-toast > goober@2.1.11" has unmet peer dependency "csstype@^3.0.10".
[15:54:28.840] warning "react-spring > @react-spring/konva@9.5.5" has unmet peer dependency "konva@>=2.6".
[15:54:28.841] warning "react-spring > @react-spring/konva@9.5.5" has unmet peer dependency "react-konva@^16.8.0 || ^17.0.0".
[15:54:28.841] warning "react-spring > @react-spring/native@9.5.5" has unmet peer dependency "react-native@>=0.58".
[15:54:28.841] warning "react-spring > @react-spring/three@9.5.5" has unmet peer dependency "@react-three/fiber@>=6.0".
[15:54:28.841] warning "react-spring > @react-spring/three@9.5.5" has unmet peer dependency "three@>=0.126".
[15:54:28.841] warning "react-spring > @react-spring/zdog@9.5.5" has unmet peer dependency "react-zdog@>=1.0".
[15:54:28.841] warning "react-spring > @react-spring/zdog@9.5.5" has unmet peer dependency "zdog@>=1.0".
[15:54:28.842] warning " > @trivago/prettier-plugin-sort-imports@4.0.0" has unmet peer dependency "@vue/compiler-sfc@3.x".
[15:54:28.863] warning Workspaces can only be enabled in private projects.
[15:54:47.222] [4/4] Building fresh packages...
[15:54:53.771] $ prisma generate || true
[15:54:54.596] Prisma schema loaded from prisma/schema.prisma
[15:54:55.520] 
[15:54:55.520] ✔ Generated Prisma Client (4.9.0 | library) to ./node_modules/@prisma/client in 232ms
[15:54:55.521] You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
[15:54:55.521] ```
[15:54:55.521] import { PrismaClient } from '@prisma/client'
[15:54:55.521] const prisma = new PrismaClient()
[15:54:55.521] ```
[15:54:55.583] Done in 58.77s.
[15:54:55.613] Detected Next.js version: 13.2.4
[15:54:55.614] Running "yarn run build"
[15:54:55.789] yarn run v1.22.17
[15:54:55.821] $ prisma generate
[15:54:56.650] Prisma schema loaded from prisma/schema.prisma
[15:54:57.585] 
[15:54:57.585] ✔ Generated Prisma Client (4.9.0 | library) to ./node_modules/@prisma/client in 233ms
[15:54:57.585] You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
[15:54:57.585] ```
[15:54:57.585] import { PrismaClient } from '@prisma/client'
[15:54:57.585] const prisma = new PrismaClient()
[15:54:57.585] ```
[15:54:57.730] ┌─────────────────────────────────────────────────────────┐
[15:54:57.730] │  Update available 4.9.0 -> 4.11.0                       │
[15:54:57.731] │  Run the following to update                            │
[15:54:57.731] │    yarn add --dev prisma@latest                         │
[15:54:57.731] │    yarn add @prisma/client@latest                       │
[15:54:57.731] └─────────────────────────────────────────────────────────┘
[15:54:57.747] $ next build
[15:54:58.322] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[15:54:58.322] This information is used to shape Next.js' roadmap and prioritize features.
[15:54:58.322] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[15:54:58.322] https://nextjs.org/telemetry
[15:54:58.323] 
[15:54:58.568] info  - Linting and checking validity of types...
[15:55:07.950] info  - Creating an optimized production build...
[15:55:08.011] warn  - You are using an experimental edge runtime, the API might change.
[15:55:40.911] <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (177kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
[15:55:50.095] warn  - Compiled with warnings
[15:55:50.096] 
[15:55:50.096] ./node_modules/@upstash/redis/esm/platforms/nodejs.js
[15:55:50.096] A Node.js API is used (process.version at line: 26) which is not supported in the Edge Runtime.
[15:55:50.096] Learn more: https://nextjs.org/docs/api-reference/edge-runtime
[15:55:50.096] 
[15:55:50.096] Import trace for requested module:
[15:55:50.096] ./node_modules/@upstash/redis/esm/platforms/nodejs.js
[15:55:50.096] ./lib/upstash.ts
[15:55:50.096] 
[15:55:50.099] info  - Collecting page data...
[15:55:51.115] PrismaClientInitializationError: 
[15:55:51.115] Invalid `prisma.project.findMany()` invocation:
[15:55:51.115] 
[15:55:51.115] 
[15:55:51.115] Error querying the database: Server error: `ERROR HY000 (1105): unavailable: unable to connect to branch vsxwgzdfjj5w'
[15:55:51.115]     at RequestHandler.handleRequestError (/vercel/path0/node_modules/@prisma/client/runtime/index.js:31955:13)
[15:55:51.115]     at RequestHandler.handleAndLogRequestError (/vercel/path0/node_modules/@prisma/client/runtime/index.js:31913:12)
[15:55:51.115]     at /vercel/path0/node_modules/@prisma/client/runtime/index.js:32458:25
[15:55:51.116]     at async PrismaClient._executeRequest (/vercel/path0/node_modules/@prisma/client/runtime/index.js:33022:22)
[15:55:51.117]     at async PrismaClient._request (/vercel/path0/node_modules/@prisma/client/runtime/index.js:32994:16)
[15:55:51.117]     at async getStaticPaths (/vercel/path0/.next/server/pages/_root/[domain].js:187:21)
[15:55:51.117]     at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:614:33)
[15:55:51.117]     at async /vercel/path0/node_modules/next/dist/build/utils.js:1024:115
[15:55:51.117]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20) {
[15:55:51.117]   clientVersion: '4.9.0',
[15:55:51.117]   errorCode: undefined
[15:55:51.118] }
[15:55:51.118] 
[15:55:51.118] > Build error occurred
[15:55:51.120] Error: Failed to collect page data for /_root/[domain]
[15:55:51.120]     at /vercel/path0/node_modules/next/dist/build/utils.js:1055:15 {
[15:55:51.120]   type: 'Error'
[15:55:51.120] }
[15:55:51.235] error Command failed with exit code 1.
[15:55:51.235] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[15:55:51.257] Error: Command "yarn run build" exited with 1
[15:55:51.842] BUILD_FAILED: Command "yarn run build" exited with 1
```

**Comment by sofiane-soufi** [comment]
> **It's still wrong**
> 
> ```
> [15:53:55.249] Running build in Washington, D.C., USA (East) – iad1
> [15:53:55.302] Cloning github.com/love2wind/dub (Branch: main, Commit: 41e6d65)
> [15:53:55.308] Skipping build cache, deployment was triggered without cache.
> [15:53:55.651] Cloning completed: 349.227ms
> [15:53:55.786] Running "vercel build"
> [15:53:56.236] Vercel CLI 28.16.15
> [15:53:56.514] Installing dependencies...
> [15:53:56.811] yarn install v1.22.17
> [15:53:56.887] [1/4] Resolving packages...
> [15:53:57.203] [2/4] Fetching packages...
> [15:54:28.830] [3/4] Linking dependencies...
> [15:54:28.839] warning " > focus-trap-react@10.0.1" has unmet peer dependency "prop-types@^15.8.1".
> [15:54:28.839] warning "mailing-core > mjml-react > react-reconciler@0.26.2" has incorrect peer dependency "react@^17.0.2".
> [15:54:28.840] warning "react-hot-toast > goober@2.1.11" has unmet peer dependency "csstype@^3.0.10".
> [15:54:28.840] warning "react-spring > @react-spring/konva@9.5.5" has unmet peer dependency "konva@>=2.6".
> [15:54:28.841] warning "react-spring > @react-spring/konva@9.5.5" has unmet peer dependency "react-konva@^16.8.0 || ^17.0.0".
> [15:54:28.841] warning "react-spring > @react-spring/native@9.5.5" has unmet peer dependency "react-native@>=0.58".
> [15:54:28.841] warning "react-spring > @react-spring/three@9.5.5" has unmet peer dependency "@react-three/fiber@>=6.0".
> [15:54:28.841] warning "react-spring > @react-spring/three@9.5.5" has unmet peer dependency "three@>=0.126".
> [15:54:28.841] warning "react-spring > @react-spring/zdog@9.5.5" has unmet peer dependency "react-zdog@>=1.0".
> [15:54:28.841] warning "react-spring > @react-spring/zdog@9.5.5" has unmet peer dependency "zdog@>=1.0".
> [15:54:28.842] warning " > @trivago/prettier-plugin-sort-imports@4.0.0" has unmet peer dependency "@vue/compiler-sfc@3.x".
> [15:54:28.863] warning Workspaces can only be enabled in private projects.
> [15:54:47.222] [4/4] Building fresh packages...
> [15:54:53.771] $ prisma generate || true
> [15:54:54.596] Prisma schema loaded from prisma/schema.prisma
> [15:54:55.520] 
> [15:54:55.520] ✔ Generated Prisma Client (4.9.0 | library) to ./node_modules/@prisma/client in 232ms
> [15:54:55.521] You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
> [15:54:55.521] ```
> [15:54:55.521] import { PrismaClient } from '@prisma/client'
> [15:54:55.521] const prisma = new PrismaClient()
> [15:54:55.521] ```
> [15:54:55.583] Done in 58.77s.
> [15:54:55.613] Detected Next.js version: 13.2.4
> [15:54:55.614] Running "yarn run build"
> [15:54:55.789] yarn run v1.22.17
> [15:54:55.821] $ prisma generate
> [15:54:56.650] Prisma schema loaded from prisma/schema.prisma
> [15:54:57.585] 
> [15:54:57.585] ✔ Generated Prisma Client (4.9.0 | library) to ./node_modules/@prisma/client in 233ms
> [15:54:57.585] You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
> [15:54:57.585] ```
> [15:54:57.585] import { PrismaClient } from '@prisma/client'
> [15:54:57.585] const prisma = new PrismaClient()
> [15:54:57.585] ```
> [15:54:57.730] ┌─────────────────────────────────────────────────────────┐
> [15:54:57.730] │  Update available 4.9.0 -> 4.11.0                       │
> [15:54:57.731] │  Run the following to update                            │
> [15:54:57.731] │    yarn add --dev prisma@latest                         │
> [15:54:57.731] │    yarn add @prisma/client@latest                       │
> [15:54:57.731] └─────────────────────────────────────────────────────────┘
> [15:54:57.747] $ next build
> [15:54:58.322] Attention: Next.js now collects completely anonymous telemetry regarding usage.
> [15:54:58.322] This information is used to shape Next.js' roadmap and prioritize features.
> [15:54:58.322] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
> [15:54:58.322] https://nextjs.org/telemetry
> [15:54:58.323] 
> [15:54:58.568] info  - Linting and checking validity of types...
> [15:55:07.950] info  - Creating an optimized production build...
> [15:55:08.011] warn  - You are using an experimental edge runtime, the API might change.
> [15:55:40.911] <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (177kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
> [15:55:50.095] warn  - Compiled with warnings
> [15:55:50.096] 
> [15:55:50.096] ./node_modules/@upstash/redis/esm/platforms/nodejs.js
> [15:55:50.096] A Node.js API is used (process.version at line: 26) which is not supported in the Edge Runtime.
> [15:55:50.096] Learn more: https://nextjs.org/docs/api-reference/edge-runtime
> [15:55:50.096] 
> [15:55:50.096] Import trace for requested module:
> [15:55:50.096] ./node_modules/@upstash/redis/esm/platforms/nodejs.js
> [15:55:50.096] ./lib/upstash.ts
> [15:55:50.096] 
> [15:55:50.099] info  - Collecting page data...
> [15:55:51.115] PrismaClientInitializationError: 
> [15:55:51.115] Invalid `prisma.project.findMany()` invocation:
> [15:55:51.115] 
> [15:55:51.115] 
> [15:55:51.115] Error querying the database: Server error: `ERROR HY000 (1105): unavailable: unable to connect to branch vsxwgzdfjj5w'
> [15:55:51.115]     at RequestHandler.handleRequestError (/vercel/path0/node_modules/@prisma/client/runtime/index.js:31955:13)
> [15:55:51.115]     at RequestHandler.handleAndLogRequestError (/vercel/path0/node_modules/@prisma/client/runtime/index.js:31913:12)
> [15:55:51.115]     at /vercel/path0/node_modules/@prisma/client/runtime/index.js:32458:25
> [15:55:51.116]     at async PrismaClient._executeRequest (/vercel/path0/node_modules/@prisma/client/runtime/index.js:33022:22)
> [15:55:51.117]     at async PrismaClient._request (/vercel/path0/node_modules/@prisma/client/runtime/index.js:32994:16)
> [15:55:51.117]     at async getStaticPaths (/vercel/path0/.next/server/pages/_root/[domain].js:187:21)
> [15:55:51.117]     at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:614:33)
> [15:55:51.117]     at async /vercel/path0/node_modules/next/dist/build/utils.js:1024:115
> [15:55:51.117]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20) {
> [15:55:51.117]   clientVersion: '4.9.0',
> [15:55:51.117]   errorCode: undefined
> [15:55:51.118] }
> [15:55:51.118] 
> [15:55:51.118] > Build error occurred
> [15:55:51.120] Error: Failed to collect page data for /_root/[domain]
> [15:55:51.120]     at /vercel/path0/node_modules/next/dist/build/utils.js:1055:15 {
> [15:55:51.120]   type: 'Error'
> [15:55:51.120] }
> [15:55:51.235] error Command failed with exit code 1.
> [15:55:51.235] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> [15:55:51.257] Error: Command "yarn run build" exited with 1
> [15:55:51.842] BUILD_FAILED: Command "yarn run build" exited with 1
> ```

It looks like you're missing Redis in your .env file:

`UPSTASH_REDIS_REST_URL`
`UPSTASH_REDIS_REST_TOKEN`
